99714 client routing
DTS-STN/secure-client-hub pull request #209
Opened 2023-02-06 17:17 UTC by numbap

## [ADO-99714](https://dev.azure.com/VP-BD/DECD/_workitems/edit/99714)
Fixed [AB#99714](https://dev.azure.com/VP-BD/d5ca3cd4-19cb-4c8c-b3e6-a7068f4677e4/_workitems/edit/99714)

### Description

List of proposed changes:

- Used beta DS to add Link to menu
- Testing build. Please do not merge yet. 

### What to test for/How to test

### Additional Notes

2023-02-06 20:38 UTC, nibivi77 reviewed
Seems to function properly. The only thing I noticed is when you navigate to another page, the drop-down menu stays open.

![image](https://user-images.githubusercontent.com/77116011/217079776-469bc039-d69b-4335-a755-4969d691816b.png)

I suspect that this comes from Design System. Do we care about this?

2023-02-08 14:31 UTC, DaceyTom2 submitted a review, later dismissed
Seems to work well. The first time I clicked on the menu it wasn't changing the page. Worth keeping a mental note to check from time to time

2023-02-10 16:25 UTC, shewood requested changes
to skip an entire test you just add .skip like this
it.skip('Validate da....

2023-02-10 19:45 UTC, nibivi77 requested changes

2023-02-10 19:45 UTC, nibivi77 commented on components/Layout.js
> +        lang={!props.locale ? 'en' : props.locale}
I think `lang` prop can be removed since its not being used in <MetaData> and that `language` is doing the same thing.

2023-02-10 20:23 UTC, nibivi77 approved these changes
Awesome!

2023-02-16 19:53 UTC, closed without merging